spring:
  application:
    name: schooling

  autoconfigure:
    exclude:
#    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
#    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  data:
    mongodb:
      database: schooling
      uri: mongodb://localhost/schooling

